version: "2"
services:
  openmrs-mysql-db:
    image: uwitech/mysql
    container_name: &db openmrs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: shr
      MYSQL_USER: &openmrs_db_user admin
      MYSQL_PASSWORD: &openmrs_db_password Admin123
      MYSQL_DATABASE: &openmrs_db openmrs
  postgresql-openxds:
    image: uwitech/postgresql
    container_name: postgresql-openxds
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=openxds
      - POSTGRES_DB=openxds
      - POSTGRES_PASSWORD=openxds
  openxds:
    image: uwitech/openxds
    ports:
      - "8010:8010"
      - "8020:8020"
    container_name: openxds
    depends_on:
      - postgresql-openxds
  openmrs:
    image: uwitech/oshr
    ports:
      - "8080:8080"
    container_name: openmrs-platform
    depends_on:
      - openmrs-mysql-db
      - openxds
    environment:
      POSTGRES_USER: openxds
      POSTGRES_PASSWORD: openxds
      MYSQL_ROOT_PASSWORD: shr
      MYSQL_USER: *openmrs_db_user
      MYSQL_PASSWORD: *openmrs_db_password
      MYSQL_DATABASE: *openmrs_db
      MYSQL_HOST: *db
      MYSQL_PORT: 3306
