version: "2"
services:
  db:
    image: uwitech/mysql
    container_name: &db openmrs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: shr
      MYSQL_USER: &openmrs_db_user admin
      MYSQL_PASSWORD: &openmrs_db_password Admin123
      MYSQL_DATABASE: &openmrs_db openmrs
  postgresql:
    image: uwitech/postgresql
    container_name: &postgresql openmrs-postgresql
    environment:
      POSTGRES_USER: openxds
      POSTGRES_DB: openxds
      POSTGRES_PASSWORD: openxds
  openmrs:
    image: uwitech/oshr
    ports:
      - "8080:8080"
    container_name: openmrs-platform
    depends_on:
      - db
      - postgresql
    environment:
      POSTGRES_USER: openxds
      POSTGRES_PASSWORD: openxds
      MYSQL_ROOT_PASSWORD: shr
      MYSQL_USER: *openmrs_db_user
      MYSQL_PASSWORD: *openmrs_db_password
      MYSQL_DATABASE: *openmrs_db
      MYSQL_HOST: *db
      MYSQL_PORT: 3306
